pool:
  vmImage: "Ubuntu 16.04"

pr:
  - master

variables:
  buildConfiguration: "Release"

stages:
- stage: build_source
  displayName: build source
  dependsOn: [] 
  jobs:
  - job: build_angular_designer
    displayName: build angular designer
    steps:
    - task: NodeTool@0
      displayName: set node to version 12.x
      inputs:
        versionSpec: "12.x"
    - script: npm run build -- --prod
      displayName: npm build --prod
      workingDirectory: src/orbital-designer
    - task: CopyFiles@2
      displayName: move designer build to artifacts
      inputs:
        SourceFolder: "$(System.DefaultWorkingDirectory)/src/orbital-designer/dist"
        Contents: |
          *
          orbital-designer/**
      TargetFolder: "$(Build.ArtifactStagingDirectory)"
    - task: PublishBuildArtifacts@1
      displayName: publish designer build to artifacts
  - job: publish_release_scripts
    dispalyName: publish release scripts
    steps:
    - task: CopyFiles@2
      displayName: move scripts to artifacts
      inputs:
        SourceFolder: "$(System.DefaultWorkingDirectory)/scripts"
        Contents: *
    - task: PublishBuildArtifacts@1
      displayName: publish scripts build to artifacts
  - job: build_dotnet_mock_server
    displayName: build dotnet mock server
    steps:
    - task: DotNetCoreCLI@2
      displayName: dotnet publish
      inputs:
        command: publish
        arguments: "--configuration $(buildConfiguration) --output $(System.DefaultWorkingDirectory)/mock/build"
        workingDirectory: src/Orbital.Mock.Server/
        publishWebProjects: false
        modifyOutputPath: true
        zipAfterPublish: true
  - job: build_dotnet_mock_server_win_x64
    displayName: build dotnet mock server win x64
    steps:
    - task: DotNetCoreCLI@2
      displayName: dotnet publish win x64
      inputs:
        command: publish
        arguments: "--configuration $(buildConfiguration) --output $(System.DefaultWorkingDirectory)/mock/build" --runtime win-x64"
        workingDirectory: src/Orbital.Mock.Server/
        publishWebProjects: false
        modifyOutputPath: true
        zipAfterPublish: true
  - job: build_dotnet_mock_server_win_x64
    displayName: build dotnet mock server win x64
    steps:
    - task: DotNetCoreCLI@2
      displayName: dotnet publish linux x64
      inputs:
        command: publish
        arguments: "--configuration $(buildConfiguration) --output $(System.DefaultWorkingDirectory)/mock/build" --runtime linux-x64"
        workingDirectory: src/Orbital.Mock.Server/
        publishWebProjects: false
        modifyOutputPath: true
        zipAfterPublish: true
  - job: build_dotnet_mock_server_win_x64
    displayName: build dotnet mock server win x64
    steps:
    - task: DotNetCoreCLI@2
      displayName: dotnet publish osx x64
      inputs:
        command: publish
        arguments: "--configuration $(buildConfiguration) --output $(System.DefaultWorkingDirectory)/mock/build" --runtime osx-x64"
        workingDirectory: src/Orbital.Mock.Server/
        publishWebProjects: false
        modifyOutputPath: true
        zipAfterPublish: true
- stage: build_containers
  displayName: build containers
  dependsOn: [] 
  jobs:
  - job: build mock server container
    steps:
    - task: NuGetCommand@2
      displayName: install git version tool
      inputs:
        command: custom
        arguments: install GitVersion.CommandLine -Version 4.0.0 -OutputDirectory $(Build.BinariesDirectory)/tools -ExcludeVersion
    - script: |
        chmod -R 755 $(Build.BinariesDirectory)/tools/GitVersion.CommandLine/tools/
        mkdir $(System.DefaultWorkingDirectory)/gitversion && touch $(System.DefaultWorkingDirectory)/gitversion/gitversionvariables.json
        mono $(Build.BinariesDirectory)/tools/GitVersion.CommandLine/tools/GitVersion.exe /output json /nofetch > $(System.DefaultWorkingDirectory)/gitversion/gitversionvariables.json
        mono $(Build.BinariesDirectory)/tools/GitVersion.CommandLine/tools/GitVersion.exe /output buildserver /nofetch
      displayName: set git version to environment variables
    - task: Docker@2
      displayName: build mock server container and push to Foci Container Registry
      inputs:
        command: "buildAndPush"
        containerRegistry: "Foci Container Registry"
        repository: "orbitalmock"
        buildContext: "$(System.DefaultWorkingDirectory)"
        dockerfile: "$(System.DefaultWorkingDirectory)/docker/mock/Dockerfile"
        tags: |
          $(GitVersion.SemVer)
    - task: CopyFiles@2
      displayName: Move gitversion variables to artifact directory
      inputs:
        SourceFolder: "$(System.DefaultWorkingDirectory)/gitversion"
        Contents: |
          *
        TargetFolder: "$(Build.ArtifactStagingDirectory)"
    - task: PublishBuildArtifacts@1
      displayName: publish git version to artifacts
  - job: build mock server container
    steps:
    - task: NuGetCommand@2
      displayName: install git version tool
      inputs:
        command: custom
        arguments: install GitVersion.CommandLine -Version 4.0.0 -OutputDirectory $(Build.BinariesDirectory)/tools -ExcludeVersion
    - script: |
        chmod -R 755 $(Build.BinariesDirectory)/tools/GitVersion.CommandLine/tools/
        mkdir $(System.DefaultWorkingDirectory)/gitversion && touch $(System.DefaultWorkingDirectory)/gitversion/gitversionvariables.json
        mono $(Build.BinariesDirectory)/tools/GitVersion.CommandLine/tools/GitVersion.exe /output json /nofetch > $(System.DefaultWorkingDirectory)/gitversion/gitversionvariables.json
        mono $(Build.BinariesDirectory)/tools/GitVersion.CommandLine/tools/GitVersion.exe /output buildserver /nofetch
      displayName: set git version to environment variables
    - task: Docker@2
      displayName: "buildAndPush Orbital Designer"
      inputs:
        command: "buildAndPush"
        containerRegistry: "Foci Container Registry"
        repository: "orbitaldesigner"
        buildContext: "$(System.DefaultWorkingDirectory)"
        dockerfile: "$(System.DefaultWorkingDirectory)/docker/designer/Dockerfile"
        tags: |
          $(GitVersion.SemVer)