trigger:
  branches:
    include:
      - '*'
    exclude:
      - master
  paths:
    include:
      - src/orbital-designer/*
      - azure-pipelines-designer.yml
      
variables:
  buildConfiguration: 'Release'

resources:
  containers:
  - container: node
    image: selenium/node-chrome:latest
    options: --user 0:0

strategy:
  matrix:
    'Ubuntu 16.04':
      image: 'ubuntu-16.04'
    'Ubuntu 18.04':
      image: 'ubuntu-18.04'

stages:
- stage: test
  dependsOn: [] 
  jobs:
  - job: test_and_publish
    displayName: test and publish
    pool:
      vmImage: $(image)
    steps:
    - task: Npm@1
      displayName: 'npm ci'
      inputs:
        command: ci   
        workingDir: './src/orbital-designer' 
  
    - task: Npm@1
      displayName: 'npm run test-ci'
      inputs:
        command: custom
        customCommand: run test-ci
        workingDir: './src/orbital-designer' 

    - task: PublishCodeCoverageResults@1
      displayName: 'Publish angular code coverage results'
      condition: succeededOrFailed()
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: './src/coverage/cobertura-coverage.xml'
        reportDirectory: './src/coverage'
        failIfCoverageEmpty: true

    - task: PublishTestResults@2
      displayName: 'Publish angular test results'
      condition: succeededOrFailed()
      inputs:
        searchFolder: $(System.DefaultWorkingDirectory)/src/junit
        testRunTitle: Angular
        testResultsFormat: JUnit
        testResultsFiles: "**/TESTS*.xml"

    - task: Npm@1
      displayName: 'npm run lint --format=stylish'
      inputs:
        command: custom
        customCommand: run lint --  --format=stylish
        workingDir: './src/orbital-designer' 

    - task: Npm@1
      displayName: 'Run angular E2E tests'
      inputs:
        command: custom
        customCommand: run e2e
        workingDir: '$(System.DefaultWorkingDirectory)/src/orbital-designer' 

    - task: PublishTestResults@2
      displayName: 'Publish angular E2E test results'
      condition: succeededOrFailed()
      inputs:
        searchFolder: $(System.DefaultWorkingDirectory)/src/orbital-designer/e2e/junit
        testRunTitle: Angular_E2E
        testResultsFormat: JUnit
        testResultsFiles: "**/junit*.xml"